name: Unity CI/CD

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  cs-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.39f1

      - name: Generate .csproj files via Unity
        run: |
          xvfb-run --auto-servernum \
          unity-editor -batchmode -quit -projectPath . -executeMethod UnityEditor.SyncVS.SyncSolution

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build all C# projects
        id: buildcheck
        run: |
          echo "Building all .csproj files..."
          for csproj in $(find . -name "*.csproj"); do
            echo "Building $csproj"
            dotnet restore "$csproj"
            dotnet build "$csproj" --configuration Release --no-restore
          done

      - name: Comment build result on PR
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            MSG="✅ Unity C# build succeeded. No syntax errors found."
          else
            MSG="❌ Unity C# build failed. Please fix build errors before merging."
          fi

          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "Commenting on PR #$PR_NUMBER"
          gh api repos/${{ github.repository }}/issues/$PR_NUMBER/comments -f body="$MSG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
