name: Unity CI/CD

on:
    workflow_dispatch:
    pull_request:

jobs:
  unity-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Activate Unity license
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.20f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2022.3.20f1
          checkVersion: true
          testMode: all
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Post test results
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          JOB_STATUS: ${{ job.status }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = process.env.JOB_STATUS;
            const message = status === 'success'
              ? '**SUCCESS!**: No errors in Editor and Play Mode.'
              : '**FAILURE!**: Errors found in Editor or Play Mode.';
              
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
