name: Unity Code Check (No License)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unity-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Unity Editor
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.20f1

      - name: Run Unity
        run: |
          mkdir -p Logs
          xvfb-run --auto-servernum \
          unity-editor -batchmode -nographics -quit -projectPath . -logFile Logs/Unity.log || true

      - name: Check Unity logs for errors
        run: |
          echo "=== Checking for Errors in Unity Log ==="
          ERRORS=$(grep -E "(Error|Exception)" Logs/Unity.log || true)
          
          if [ -n "$ERRORS" ]; then
            echo "FAILURE!\nFailed due to Unity Editor errors!"
            echo "$ERRORS"
            exit 1
          else
            echo "SUCCESS!\nNo errors found in Unity logs."
          fi
