name: C# Build Check on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (for non-interactive environment)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Find and build C# projects
        id: buildcheck
        run: |
          PROJS=$(find . -name '*.csproj')
          if [ -z "$PROJS" ]; then
            echo "No .csproj files found, exiting."
            exit 1
          fi

          BUILD_FAILED=0

          for proj in $PROJS; do
            dotnet restore "$proj"
            dotnet build "$proj" --configuration Release --no-restore || BUILD_FAILED=1
          done

          echo "failed=$BUILD_FAILED" >> $GITHUB_OUTPUT

          if [ $BUILD_FAILED -eq 1 ]; then
            exit 1
          fi

      - name: Post build result comment on PR
        if: always() && steps.buildcheck.outputs.failed != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          if [ "${{ steps.buildcheck.outputs.failed }}" == "0" ]; then
            gh api repos/${{ github.repository }}/issues/$PR_NUM/comments -f body="✅ C# build succeeded."
          else
            gh api repos/${{ github.repository }}/issues/$PR_NUM/comments -f body="❌ C# build failed. Please fix errors before merging."
          fi
