name: C# Build Check on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build C# Projects
        id: build
        shell: pwsh
        run: |
          $errors = @()
          $failed = $false
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            $output = dotnet build $_.FullName --nologo --no-restore 2>&1
            if ($LASTEXITCODE -ne 0) {
              $failed = $true
              $output | Where-Object { $_ -match 'error' } | Select-Object -First 10 | ForEach-Object {
                $errors += ($_ -replace '\s+', ' ')
              }
            }
          }

          "failed=$failed" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
          "errors<<EOF" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
          $errors -join "`n" | Out-File -Append -FilePath $env:GITHUB_OUTPUT
          "EOF" | Out-File -Append -FilePath $env:GITHUB_OUTPUT

          if ($failed) { exit 1 }

      - name: Comment on PR
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $pr = "${{ github.event.pull_request.number }}"
          $failed = "${{ steps.build.outputs.failed }}"
          $errors = "${{ steps.build.outputs.errors }}"
          if ($failed -eq "True") {
            gh pr comment $pr -b "❌ C# build failed. Please fix errors before merging:`n`n```\n$errors\n```"
          } else {
            gh pr comment $pr -b "✅ C# build succeeded."
          }
