name: Unity CI/CD

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build C# projects
        id: buildcheck
        run: |
          BUILD_FAILED=0
          ERRORS=""

          for proj in $(find . -name '*.csproj'); do
            dotnet restore "$proj"
            OUTPUT=$(dotnet build "$proj" --configuration Release --no-restore 2>&1) || BUILD_FAILED=1
            if [ $BUILD_FAILED -eq 1 ]; then
              ERRORS="${ERRORS}\n\nProject: $proj\n$OUTPUT\n--------------------"
            fi
          done

          echo "failed=$BUILD_FAILED" >> $GITHUB_OUTPUT
          echo -e "errors<<EOF" >> $GITHUB_OUTPUT
          echo -e "$ERRORS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          [ $BUILD_FAILED -eq 1 ] && exit 1

      - name: Comment result on PR
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ steps.buildcheck.outputs.failed }}" == "0" ]; then
            MSG="✅ C# build succeeded. No syntax errors found."
          else
            MSG="❌ C# build failed. Please fix the errors before merging.\n\nErrors:\n```\n${{ steps.buildcheck.outputs.errors }}\n```"
          fi

          PR_NUM="${{ github.event.pull_request.number }}"
          gh api repos/${{ github.repository }}/issues/$PR_NUM/comments -f body="$MSG"
